name: Build and Deploy

on:
  repository_dispatch:
    types: [start-build]

jobs:
  build:
    name: SSH & Docker Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::448397505978:role/GitHubOIDCRole
          aws-region: us-east-1

      - name: Connect to EC2 & Build
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@<EC2_PUBLIC_IP> << 'EOF'
            cd /home/ubuntu/app
            docker build -t my-app .
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com
            docker tag my-app:latest 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
            docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
          EOF

